### PR TITLE
Recursive Bug removed

### LINKED ISSUE #24: The data and figs for the report creation are copied recursively
In each generation of a report the data and figs folders used to create the PDF report file are copied recursively. For example:

```
(acs@dellx) (quarters-titles % u=) ~/devel/grimoirelab-manuscripts-fork-acs $ ls -l bitergia-servers/opnfv/report_data/figs/figs/data/figs/data
total 804
drwxrwxr-x 2 acs acs   4096 mar  1 14:40 activity
....
```

### PR DESCRIPTION
**Pull request by Prabhat-IIT**
Fixes #24 
I've removed the bug and put all the `.csv` files in `data` folder and all the `.eps` file in `figs` folder

### CODE REVIEW

**Comment by aswanipranjal** [comment]
Hey @Prabhat-IIT, Thank you for the PR. I'd like to add a few points:
- When you are committing, Try to write meaningful commit messages so that in the future other developers can understand what exactly that commit did. Start by giving the commit a title if it fixes an issue, ex: `Fixes #24` in your case, and then describing what the commit did. 
- Also, you should merge both the commits into one as the second commit doesn't add any functionality.

Rest looks good to me.

**Comment by Prabhat-IIT** [comment]
Everyone has its own style of writing commits. Every organisation has its own commit guidelines. Since, I couldn't find any guidelines as of now I would like to wait for the mentors to comment and let me know about the commit and style guidelines. Rest I'll surely merge both commits into one Thanks!

**Comment by acs** [comment]
> Everyone has its own style of writing commits. Every organisation has its own commit guidelines. Since, I couldn't find any guidelines as of now I would like to wait for the mentors to comment and let me know about the commit and style guidelines

In GrimoireLab we have as reference:

https://chris.beams.io/posts/git-commit/

**Comment by Prabhat-IIT** [comment]
Thanks @acs  I'll follow them for sure :)

**Comment by jgbarah** [comment]
Waiting for @acs to chime in ;-)

**Comment by Prabhat-IIT** [comment]
@acs  I humbly request you to review the pr :)

**Comment by Prabhat-IIT** [comment]
@acs

**Comment by jgbarah** [comment]
@acs if you have nothing against this pr, I'm about to merge it...

**Comment by acs** [comment]
I am sorry about the delay dealing with this ticket. In a quick look I have not seen strange logic or code. Probably tomorrow morning I can take a look with more care and test it.

**Comment by Prabhat-IIT** [comment]
My pleasure @acs I think @jgbarah  can do the necessary rebase while merging the pr after that you can close the issue :)

**Comment by acs** [comment]
Added in the commit:

https://github.com/chaoss/grimoirelab-manuscripts/commit/ef560ef8b5a868bac1c097309cdeb72e870f7665

Thanks  @Prabhat-IIT

**Pull request closed without merging**
