### PR TITLE
[report] Add functionality to calculate PROJECT ACTIVITY section of the report

### PR DESCRIPTION
**Pull request by aswanipranjal**
This PR proposes to add the `project activity` section of the report for `git`, `github_issues`
and `github_prs` data sources.

- This PR adds the `get_sec_project_activity()` function which calculates the PROJECT ACTIVITY section of the report and stores the data into a `project_activity` folder.
- This PR also merges `create_csv_from_df` and `create_fig_from_df` into `create_csv_fig_from_df` function so that the code is a bit less cluttered  and is easier to usage.

### CODE REVIEW

**Comment by aswanipranjal** [comment]
@valeriocos @jgbarah I think this PR is big enough on it's own and I should create a separate PR adding the tests for the reports. Will that be okay with you?

**Comment by valeriocos** [comment]
@aswanipranjal, I agree with you. You could also split the 3 bullet points listed in the description of this PR in 3 different PRs.

**Comment by aswanipranjal** [comment]
@valeriocos I am dividing this PR into 4 parts, one for reports section and the other 3 for the 3 data sources.

**Comment by aswanipranjal** [comment]
@valeriocos I am finished with the PRs, please review?

**Pull request merged**
