### PR TITLE
[tests] Update git_commit.json data

### PR DESCRIPTION
**Pull request by aswanipranjal**
This PR removes the old data from tests/data/git_commit.json file and stores `git` data from the [perceval](https://github.com/chaoss/grimoirelab-perceval.git) repository in it.

### CODE REVIEW

**Comment by aswanipranjal** [comment]
@valeriocos please review?

**Comment by valeriocos** [comment]
I cannot see the content of git_commit.json. Just to be sure I understood it right, you are replacing that content with the enriched data obtained from Perceval repo?

**Comment by aswanipranjal** [comment]
Yes @valeriocos

**Comment by aswanipranjal** [comment]
Thankyou!

**Pull request merged**
