### PR TITLE
Add functionality to calculate project_activity for git

### PR DESCRIPTION
**Pull request by aswanipranjal**
This PR adds the functionality to calculate project_activity section of the report for the git data source using the project_activity function.
It generates the timeseries aggregations for Commits class (Authors class already generates a timeseries which is being added to the function directly) for a given time interval.

This PR also adds tests and data for the timeseries generated.

### CODE REVIEW

**Comment by aswanipranjal** [comment]
@valeriocos can you please review this and the other two PRs too?

**Comment by valeriocos** [comment]
The PR looks good to me, but I don't understand why the coverage has decreased. Do you know why? Have you tried to run coveralls (https://pypi.org/project/coveralls/) locally to see which lines are missing?

**Comment by aswanipranjal** [comment]
I haven't tried Coveralls, but I am on it! Thanks!

**Comment by aswanipranjal** [comment]
screen shot 2018-08-03 at 11 53 17 am
screen shot 2018-08-03 at 11 53 28 am
These are the lines that are unreachable at the moment because I changed the tests. Hence the coverage has decreased.

**Comment by valeriocos** [comment]
Thank you, @aswanipranjal

**Comment by valeriocos** [comment]
LGTM

**Pull request merged**
